# Use custom format
format = '''
[┌──](bold #ff0000)[󰉋 ](bold #52b0ef)$directory$username$hostname$rust$package$git_branch$git_commit$git_state$git_metrics$git_status$shell
[└─](bold #ff0000)[❯](#50FA7B) '''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false



# [hostname]
# ssh_only = false
# format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
# trim_at = '.companyname.com'
# disabled = false
#
#
# [username]
# style_user = 'white bold'
# style_root = 'black bold'
# format = 'user: [$user]($style) '
# disabled = false
# show_always = true

[directory]
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false
fish_style_pwd_dir_length = 1
style = "bold #52b0ef"

[shell]
fish_indicator = '󰈺 '
powershell_indicator = '_'
# bash_indicator = "bsh"
unknown_indicator = 'mystery shell'
style = 'bold #ff0000'
disabled = false

[git_status]
disabled=true # because slow in large repos
