#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 

# CHANGING BORDER COLORS
# normal_border_color
# bspc config focused_border_color "#52b0ef"
# bspc config active_border_color "#52b0ef"

# bspc config focused_border_color "#C147E9"
# bspc config active_border_color "#C147E9"

# bspc config focused_border_color "#FB2576"
# bspc config active_border_color "#FB2576"

# bspc config focused_border_color "#F44747"
# bspc config active_border_color "#F44747"

# picom
# picom &
# picom --experimental-backends --transparent-clipping &#helps in clean monocle and fullscreen mode


#styling
bspc config focused_border_color "#ff0000"
bspc config active_border_color "#ff0000"
bspc config border_width         4
bspc config window_gap          10
# bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false


## BSPC RULES
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'

bspc config ignore_ewmh_focus true #helps in forcing focus=off in some applications
bspc rule -a Brave-browser desktop='^2' follow=off 
bspc rule -a Xournalpp desktop='^4' follow=off
# bspc rule -a Alacritty desktop='^1'
# bspc rule -a Alacritty -e ncmpcpp desktop='^10'
# bspc rule -a "Alacritty:ncmpcpp" desktop='^9' follow=off
# bspc rule -a ~/scripts/ncmpcpp.sh desktop='^8' 
# bspc rule -a ~/scripts/mux.sh desktop='^1' 

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# setting zathura for tiling mode
bspc rule -a Zathura state=tiled

#executing polybar
polybar -r example &
# /home/anand/.config/polybar/launch.sh
nm-applet &

# executing feh for background
feh --bg-fill $HOME/Pictures/wallpapers/city_wallpapers/navy-blue-fluid-painting-d0x1q0mcxqzzzanx.jpg

#spawning the greenclip daemon
greenclip daemon &
 
# touchegg
touchegg &
 
# auto-cpufreq
auto-cpufreq &

# setting r rate(i copy pasted it here from .xprofile and deleted it from there)
xset r rate 200 70

# dunst 
/usr/bin/dunst &

#for setting the pointer
# xsetroot -cursor_name left_ptr &

# executing polkit gnome
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

#playerctl 
# playerctld daemon 

#allowing mouse to change focus
bspc config focus_follows_pointer true

#bspswallow 
# pgrep bspswallow || bspswallow &
# pgrep ~/.config/bspwm/bspswallow/bspswallow || ~/.config/bspwm/bspswallow/bspswallow &
pgrep ~/scripts/bspswallow/bspswallow || ~/scripts/bspswallow/bspswallow &

# another script for swallowing feature
# ~/scripts/bspwmswallow.py DEBUG &

# picom -b 
# picom &
picom --transparent-clipping &
# picom --experimental-backends --transparent-clipping &


#starting mpd
[ ! -s ~/.config/mpd/pid ] && mpd
mpd >/dev/null 2>&1 &
