gui:
  theme:
      activeBorderColor:
        - green
        - bold
      inactiveBorderColor:
        - white
      searchingActiveBorderColor:
        - cyan
        - bold
      optionsTextColor:
        - blue
      selectedLineBgColor:
        - black # set to `default` to have no background colour
      cherryPickedCommitBgColor:
        - cyan
      cherryPickedCommitFgColor:
        - blue
      unstagedChangesColor:
        - red
      defaultFgColor:
        - default
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
keybinding:
  universal:
    return: '<c-g>' # return to previous menu, will quit if there's nowhere to return
