#!/bin/bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # selected=$(find ~/work/builds ~/projects ~/ ~/work ~/personal ~/personal/yt -mindepth 1 -maxdepth 1 -type d | fzf)
    # selected=$(find ~/Desktop ~/Documents ~/gnome-projects ~/opensource ~/Projects -mindepth 1 -maxdepth 1 -type d | fzf --layout=reverse)

    selected=$(find ${1:-~/code/} -name .git -type d -prune | sed 's/.\{5\}$//' | fzf ) # this searches all the git repositories
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
